[package]
name = "hello_macro_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# 声明 hello_macro_derive crate 是过程宏(proc-macro) crate
proc-macro = true

[dependencies]
syn = "1.0.103"
quote = "1.0.21"