[package]
name = "run"
version = "0.1.0"
edition = "2021"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "./src/main.rs"

[dependencies]
syntax_example = { path = "../syntax" }
